### ISSUE TITLE
IM-OSEM-V2 Cable is to be repaired

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/PR2#1]
## Background
- It was found that one cable for IM-OSEM-V2 was off at the soldering point.
- This cable connected the micro-Dsub and the Dsub.

## Todo 
 - [x] list up what we need
 - [x] 下見する

![6c58af00-d5af-4037-a4ea-78035df9391d](https://user-images.githubusercontent.com/37787512/50325662-69e62800-0529-11e9-9159-8ba476e51182.jpg)

## Assignee
@MiyoKouseki 
@YoshinoriFujii

**Comment by YoshinoriFujii** [comment]
### Vacuum-related schedule 
- Venting is still ongoing on 16:35 JST on Jan. 7th, 2019.
- MPC is going to start from IMC area and then come to PR2 and BS area.
- Work around PR2-BS area will happen around 10am (maybe).
  - This should be checked with the person in MPC, the phone would be V9.

### schedule on 8th
- [ ] measure TFs w/o controls
  - SF-GAS
  - BF-GAS
  - BF-LVDTs for 6 dofs.
  - IM-OSEMSs for ___.
  - TM-OpLev for 3 dofs.

### schedule on 8th
- [ ] remove the tube, PR2-BS, with MPC
- [ ] open the top-chamber
- [ ] 現場保存 with photos
  - about cabling
    - [ ] clamp position

**Comment by YoshinoriFujii** [comment]
> 現場保存 with photos 

see [klog#7588](http://klog.icrr.u-tokyo.ac.jp/osl/?r=7588 "klog#7588")
photo album: [https://photos.app.goo.gl/uuQtc2q6ajdHoxKSA](https://photos.app.goo.gl/uuQtc2q6ajdHoxKSA
)

**Comment by YoshinoriFujii** [comment]
see [klog7110](http://klog.icrr.u-tokyo.ac.jp/osl/?r=7710 "klog7110").
- [ ] measure the transfer functions and confirm PR2-suspension is totally healthy.

**Comment by MiyoKouseki** [comment]
Can I close this issue?
