### ISSUE TITLE
Performance check after pumping down

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/PR2#4]
### Todo
- [ ] measure all the transfer functions
- [ ] compare with the simulation

**Comment by YoshinoriFujii** [comment]
- [ ] it looked one BF-LVDT has no signal. check this.

**Comment by MiyoKouseki** [comment]
Can I close this issue?
