### ISSUE TITLE
PR2 hardware maintenance work

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/PR2#6]
### Todo

- [ ] swap the LVDT driver for BF-V;
  - [ ] tune the gains with TF from V-exc to each coil after tuning the phase, with white noise.
  - [ ] somehow (roughly?) estimate the calibration factor.

- [ ] adjust the horizontal OSEMs position with the traverser.
  - Note that we do not have much margin in one Yaw direction.

- [x] swap the satellite boxes for IM.
  - [x] check the spectra before/after the work

**Comment by etoal83** [comment]
Satellite box replacement has done. So I checked the corresponding todos.
[klog #8928](http://klog.icrr.u-tokyo.ac.jp/osl/?r=8928)

But I wonder why just an additional capacitor in the transimpedance amplifier results in such a large improvement on the boardband noise levels of the OSEMs, as I posted to the klog above.

**Comment by MiyoKouseki** [comment]
Can I close this issue?
